### ISSUE TITLE
Tracking issue for Oppy 1.0

### ISSUE THREAD

**Issue by Perksey** [Ultz/Oppy#1]
# Development
- [x] Basic file handler/http hosting using Kestrel
- [x] Scripting handler
- [x] File autorefresh
- [ ] File browsing
- [ ] Plugin system
- [ ] Site compiler
- [ ] Inline HTML C# scripts
- [ ] Inline HTML SignalR

# Workflow
TBD
